### ISSUE TITLE
No need of relative path

### ISSUE THREAD

**Issue by shaileshpatil-work** [shaileshpatil-work/Javascript-Training#10]
https://github.com/shaileshpatil-work/Javascript-Training/blob/2800d927514e190170e11feb2cddec38c19971d1/Borders/triangles.html#L8

**Comment by abp437** [comment]
Relative Path Necessary, since the css files are placed in a separate folder and we don't need absolute in this case since we aren't loading css from an external source or cdn but from our folders itself.
Marking this as closed.
