### ISSUE TITLE
CSS elements priority is not well

### ISSUE THREAD

**Issue by shaileshpatil-work** [shaileshpatil-work/Javascript-Training#14]
https://github.com/shaileshpatil-work/Javascript-Training/blob/2800d927514e190170e11feb2cddec38c19971d1/CSS%20Grids%20Practice/Grid/gridStyle.css#L97

**Comment by abp437** [comment]
Closing this as it was resolved in PR 
https://github.com/shaileshpatil-work/Javascript-Training/pull/20
