### ISSUE TITLE
Indentation missing in complete file

### ISSUE THREAD

**Issue by shaileshpatil-work** [shaileshpatil-work/Javascript-Training#18]
https://github.com/shaileshpatil-work/Javascript-Training/blob/2800d927514e190170e11feb2cddec38c19971d1/CSS%20Grids%20Practice/table/style.css#L19

**Comment by abp437** [comment]
Closing this as it was resolved in PR 
https://github.com/shaileshpatil-work/Javascript-Training/pull/20
